name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK for compilation
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: 'maven'
      - name: Build
        run: mvn -B clean install -DskipTests
